# انتخاب تصویر پایه Node.js
FROM node:20

# مشخص کردن مسیر کاری داخل کانتینر
WORKDIR /usr/src/frontends

# کپی محتویات فولدر frontends به داخل کانتینر
COPY frontends/package*.json ./
COPY frontends/. ./

# نصب dependencies
RUN npm install

# پورت پیش‌فرض React
EXPOSE 3000

# اجرای پروژه در حالت توسعه
CMD ["npm", "run","dev"]