services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    container_name: backend
    volumes:
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      PG_USER: username
      PG_PASSWORD: password
      PG_NAME: default_database
      PG_HOST: db
      PG_PORT: 5432
      DEBUG: True

    ports:
      - "8000:8000"
    depends_on:
      - db

#  frontend:
#    build:
#      context: .
#      dockerfile: ./dockerfiles/dev/django/Dockerfile-1
#    container_name: frontends
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontends:/app
#      - /app/node_modules
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#    stdin_open: true
#    tty: true


  #  =====================================================================================================================